name: dnslib
description: A DNS client library for Dart.
version: 1.1.4
license: MIT
repository: https://github.com/yhojann-cl/dart-dnslib

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  http: ^1.4.0
  intl: ^0.20.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
